name: "Terraform & Terratest CI"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/*.md'
      - '**/docs/**'
      - '**/.github/ISSUE_TEMPLATE/**'
      - '**/.vscode/**'
      - '**/.devcontainer/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/*.md'
      - '**/docs/**'
      - '**/.github/ISSUE_TEMPLATE/**'
      - '**/.vscode/**'
      - '**/.devcontainer/**'

jobs:
  test:
    name: "Run Terratest"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' 

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0" # O la versión que prefieras

      - name: Init Go module if needed
        run: |
          if [ ! -f go.mod ]; then
            go mod init terraform-docker-modular-lab/test
          fi
          go mod tidy
        working-directory: ./test

      - name: "Run Terratest"
        working-directory: ./test
        run: |
          go test -v -timeout 30m